apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-soe-composite
  labels:
    app: front-soe-composite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-soe-composite
  template:
    metadata:
      labels:
        app: front-soe-composite
    spec:
      containers:
        - name: front-soe-composite-container
          image: senbar/front-soe-composite:latest
          ports:
            - containerPort: 80
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: front-soe-composite
spec:
  type: ClusterIP
  selector:
    app: front-soe-composite
  ports:
    - port: 80
      targetPort: 80
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: front-soe-composite
# spec:
#   type: NodePort
#   selector:
#     app: front-soe-composite
#   ports:
#     # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
#     - port: 80
#       targetPort: 80
#       # Optional field
#       # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
#       nodePort: 30007
